# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  locale: "ca"
  app.locales: ca|es
  instance: "diba"
  project_code: "starterkit"
  vus:
    ws_url: "%env(VUS_WS_URL)%"
    ws_user: "%env(VUS_WS_USER)%"
    ws_pass: "%env(VUS_WS_PASS)%"
    ws_app: "%env(VUS_WS_APP)%"
  upload_dir: "%kernel.project_dir%/var/uploads"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    App\Service\Etl\Importer\AbstractEtlImporter:
      tags: ['app.etl_importer']

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Doctrine\IndicatorQueryExtension:
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection }
    # arguments:
    #   $entityManager: "@doctrine.orm.entity_manager"
    # tags: ["api_platform.doctrine.orm.query_extension.collection"]

  App\Controller\ETLController:
    arguments:
      $uploadDir: "%env(UPLOAD_DIR)%"

  App\Service\Etl\Importer\CsvImporter:
    arguments:
      $uploadDir: "%env(UPLOAD_DIR)%"

  App\Service\Etl\Importer\Csv1610Importer:
    arguments:
      $uploadDir: "%env(UPLOAD_DIR)%"

  App\Service\Etl\Importer\Csv711Importer:
    arguments:
      $uploadDir: "%env(UPLOAD_DIR)%"

  App\Controller\LabelHierarchyController:
    tags: ["controller.service_arguments"]

  App\Controller\CsvExportController:
    tags: ["controller.service_arguments"]

  App\Controller\SyntheticSdgController:
    tags: ["controller.service_arguments"]

  App\OpenApi\CustomOpenApiFactory:
    decorates: "api_platform.openapi.factory"
    arguments: ['@App\OpenApi\CustomOpenApiFactory.inner']

  App\Service\Aggregation\RatioAggregationStrategy:
    tags: ['app.aggregation_strategy']

  App\Service\Aggregation\PopulationWeightedStrategy:
    tags: ['app.aggregation_strategy']

  App\Service\Aggregation\NumberOfBeachesWeightedStrategy:
    tags: ['app.aggregation_strategy']

  App\Service\Aggregation\CoastalAggregationStrategy:
    arguments:
      $projectDir: '%kernel.project_dir%'
    tags: ['app.aggregation_strategy']

  App\Service\Aggregation\AverageStrategy:
    tags: ['app.aggregation_strategy']

  App\Service\ETLService:
    arguments:
      $importers: !tagged_iterator app.etl_importer

  App\Service\AggregationCalculatorService:
    arguments:
      $strategies: !tagged_iterator app.aggregation_strategy

  # App\Controller\MunicipalityValueController:
  #   arguments:
  #     $repository: '@App\Repository\MunicipalityValueRepository'
